//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS2015.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HD Pro Webcam C920")]
        public string Camera {
            get {
                return ((string)(this["Camera"]));
            }
            set {
                this["Camera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double BGUniformityMin {
            get {
                return ((double)(this["BGUniformityMin"]));
            }
            set {
                this["BGUniformityMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double BGUniformityMax {
            get {
                return ((double)(this["BGUniformityMax"]));
            }
            set {
                this["BGUniformityMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SharpnessMin {
            get {
                return ((double)(this["SharpnessMin"]));
            }
            set {
                this["SharpnessMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double SharpnessMax {
            get {
                return ((double)(this["SharpnessMax"]));
            }
            set {
                this["SharpnessMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double GrayscaleDensityMin {
            get {
                return ((double)(this["GrayscaleDensityMin"]));
            }
            set {
                this["GrayscaleDensityMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GrayscaleDensityMax {
            get {
                return ((double)(this["GrayscaleDensityMax"]));
            }
            set {
                this["GrayscaleDensityMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double PhotoGlobalScore {
            get {
                return ((double)(this["PhotoGlobalScore"]));
            }
            set {
                this["PhotoGlobalScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Bitmap_HResolution {
            get {
                return ((int)(this["Bitmap_HResolution"]));
            }
            set {
                this["Bitmap_HResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Bitmap_VResolution {
            get {
                return ((int)(this["Bitmap_VResolution"]));
            }
            set {
                this["Bitmap_VResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SagemCaptureTime {
            get {
                return ((int)(this["SagemCaptureTime"]));
            }
            set {
                this["SagemCaptureTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int FP_Quality_Threshold {
            get {
                return ((int)(this["FP_Quality_Threshold"]));
            }
            set {
                this["FP_Quality_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operator")]
        public string Operator {
            get {
                return ((string)(this["Operator"]));
            }
            set {
                this["Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StationName")]
        public string StationReference {
            get {
                return ((string)(this["StationReference"]));
            }
            set {
                this["StationReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abc")]
        public string AdminPass {
            get {
                return ((string)(this["AdminPass"]));
            }
            set {
                this["AdminPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SagemOutputJPG {
            get {
                return ((bool)(this["SagemOutputJPG"]));
            }
            set {
                this["SagemOutputJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SagemOutputANSI378 {
            get {
                return ((bool)(this["SagemOutputANSI378"]));
            }
            set {
                this["SagemOutputANSI378"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SagemOutputWSQ {
            get {
                return ((bool)(this["SagemOutputWSQ"]));
            }
            set {
                this["SagemOutputWSQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CaptureCntr {
            get {
                return ((int)(this["CaptureCntr"]));
            }
            set {
                this["CaptureCntr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime SystemDate {
            get {
                return ((global::System.DateTime)(this["SystemDate"]));
            }
            set {
                this["SystemDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsCompressFinalFolder {
            get {
                return ((bool)(this["IsCompressFinalFolder"]));
            }
            set {
                this["IsCompressFinalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDeleteFinalFolder {
            get {
                return ((bool)(this["IsDeleteFinalFolder"]));
            }
            set {
                this["IsDeleteFinalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int DefaultBrightness {
            get {
                return ((int)(this["DefaultBrightness"]));
            }
            set {
                this["DefaultBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int DefaultSharpness {
            get {
                return ((int)(this["DefaultSharpness"]));
            }
            set {
                this["DefaultSharpness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int DefaultZoom {
            get {
                return ((int)(this["DefaultZoom"]));
            }
            set {
                this["DefaultZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SagemDeviceSerial {
            get {
                return ((string)(this["SagemDeviceSerial"]));
            }
            set {
                this["SagemDeviceSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135")]
        public int FaceDistance_Min {
            get {
                return ((int)(this["FaceDistance_Min"]));
            }
            set {
                this["FaceDistance_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310")]
        public int FaceDistance_Max {
            get {
                return ((int)(this["FaceDistance_Max"]));
            }
            set {
                this["FaceDistance_Max"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://philhealth.allcard.com.ph:2200/Allcard.asmx")]
        public string DCS2015_ph_com_allcard_philhealth_secura_Allcard {
            get {
                return ((string)(this["DCS2015_ph_com_allcard_philhealth_secura_Allcard"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecugenDevice {
            get {
                return ((string)(this["SecugenDevice"]));
            }
            set {
                this["SecugenDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public short Timeout_Secugen {
            get {
                return ((short)(this["Timeout_Secugen"]));
            }
            set {
                this["Timeout_Secugen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public int ImageWidth_Secugen {
            get {
                return ((int)(this["ImageWidth_Secugen"]));
            }
            set {
                this["ImageWidth_Secugen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ImageHeight_Secugen {
            get {
                return ((int)(this["ImageHeight_Secugen"]));
            }
            set {
                this["ImageHeight_Secugen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public short QualityThreshold_Secugen {
            get {
                return ((short)(this["QualityThreshold_Secugen"]));
            }
            set {
                this["QualityThreshold_Secugen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SecugenOutputANSI378 {
            get {
                return ((bool)(this["SecugenOutputANSI378"]));
            }
            set {
                this["SecugenOutputANSI378"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SecugenOutputWSQ {
            get {
                return ((bool)(this["SecugenOutputWSQ"]));
            }
            set {
                this["SecugenOutputWSQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecugenOutputJPG {
            get {
                return ((bool)(this["SecugenOutputJPG"]));
            }
            set {
                this["SecugenOutputJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignatureOutputTIFF {
            get {
                return ((bool)(this["SignatureOutputTIFF"]));
            }
            set {
                this["SignatureOutputTIFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SignatureOutputJPG {
            get {
                return ((bool)(this["SignatureOutputJPG"]));
            }
            set {
                this["SignatureOutputJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SignatureOutputBMP {
            get {
                return ((bool)(this["SignatureOutputBMP"]));
            }
            set {
                this["SignatureOutputBMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FingerScanner {
            get {
                return ((string)(this["FingerScanner"]));
            }
            set {
                this["FingerScanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserRole {
            get {
                return ((string)(this["UserRole"]));
            }
            set {
                this["UserRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataCapture_Module {
            get {
                return ((bool)(this["DataCapture_Module"]));
            }
            set {
                this["DataCapture_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Photo_Module {
            get {
                return ((bool)(this["Photo_Module"]));
            }
            set {
                this["Photo_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Biometric_Module {
            get {
                return ((bool)(this["Biometric_Module"]));
            }
            set {
                this["Biometric_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Signature_Module {
            get {
                return ((bool)(this["Signature_Module"]));
            }
            set {
                this["Signature_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Preview_Module {
            get {
                return ((bool)(this["Preview_Module"]));
            }
            set {
                this["Preview_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short LoginAuthType {
            get {
                return ((short)(this["LoginAuthType"]));
            }
            set {
                this["LoginAuthType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Captured Data")]
        public string CapturedOutputPath {
            get {
                return ((string)(this["CapturedOutputPath"]));
            }
            set {
                this["CapturedOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short OC_Photo {
            get {
                return ((short)(this["OC_Photo"]));
            }
            set {
                this["OC_Photo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short OC_Signature {
            get {
                return ((short)(this["OC_Signature"]));
            }
            set {
                this["OC_Signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplashProcessValidation {
            get {
                return ((string)(this["SplashProcessValidation"]));
            }
            set {
                this["SplashProcessValidation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Topaz Siglite")]
        public string SignatureTablet {
            get {
                return ((string)(this["SignatureTablet"]));
            }
            set {
                this["SignatureTablet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short ScanFingerType {
            get {
                return ((short)(this["ScanFingerType"]));
            }
            set {
                this["ScanFingerType"] = value;
            }
        }
    }
}
